# Define a dictionary to map language codes to language names
languages = {
    "ar": "Arabic",
    "az": "Azerbaijani",
    "eu": "Basque",
    "bn": "Bengali",
    "ca": "Catalan",
    "zh": "Chinese",
    "da": "Danish",
    "nl": "Dutch",
    "en": "English",
    "fi": "Finnish",
    "fr": "French",
    "de": "German",
    "el": "Greek",
    "he": "Hebrew",
    "hi": "Hinglish",
    "hu": "Hungarian",
    "id": "Indonesian",
    "it": "Italian",
    "kk": "Kazakh",
    "ne": "Nepali",
    "no": "Norwegian",
    "pt": "Portuguese",
    "ro": "Romanian",
    "ru": "Russian",
    "sl": "Slovene",
    "es": "Spanish",
    "sv": "Swedish",
    "tg": "Tajik",
    "tr": "Turkish"
}
